language: node_js

sudo: false

matrix:
  include:
  - node_js: 8
    script:
      - npm run-script lint
      - npm run-script test-with-coverage

node_js:
- 6
- 7
- 8
- 9
- 10

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

after_success:
  - npm run coverage

notifications:
  email: false